services:
  api-gateway:
    build:
      context: ./Backend/Gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - stakeholders-service
      - blogs-service
      - followers-service
      - tours-service
      - purchase-service
    networks:
      - app-network

  stakeholders-service:
    build:
      context: ./Backend/Stakeholders
      dockerfile: Dockerfile
    container_name: stakeholders
    restart: always
    depends_on:
      - database
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: stakeholders
        fluentd-async: "true"
    expose:
      - "8080"
      - "50051"
    ports:
      - "50051:50051"
    networks:
      - app-network

  database:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tourist_app
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - app-network

  frontend:
    build: ./Frontend/tourist-app-front
    container_name: frontend
    ports:
      - "4200:4200"
    networks:
      - app-network

  blogs-service:
    build:
      context: ./Backend/Blogs
      dockerfile: Blogs.API/Dockerfile
    container_name: blogs
    restart: no
    depends_on:
      - blogs-database
    environment:
      - ConnectionStrings__DefaultConnection=Host=blogs-database;Database=blogs_db;Username=postgres;Password=root
    expose:
      - "8080"
    networks:
      - app-network

  blogs-database:
    image: postgres:16
    container_name: blogs-db
    restart: no
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: blogs_db
    volumes:
      - blogs-database-data:/var/lib/postgresql/data
    networks:
      - app-network

  followers-service:
    build:
      context: ./Backend/Followers/follower-service
      dockerfile: Dockerfile
    container_name: followers
    restart: always
    depends_on:
      - neo4j-db
    environment:
      SPRING_NEO4J_URI: bolt://neo4j-db:7687
      SPRING_NEO4J_AUTHENTICATION_USERNAME: neo4j
      SPRING_NEO4J_AUTHENTICATION_PASSWORD: password
    expose:
      - "8082"
    networks:
      - app-network

  tours-service:
    build:
      context: ./Backend/Tours/tour-service
      dockerfile: Dockerfile
    container_name: tours
    restart: always
    depends_on:
      - tours-neo4j
    environment:
      SPRING_NEO4J_URI: bolt://tours-neo4j:7687
      SPRING_NEO4J_AUTHENTICATION_USERNAME: neo4j
      SPRING_NEO4J_AUTHENTICATION_PASSWORD: notverysecret
    ports:
      - "8083:8083"
    expose:
      - "8083"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network

  neo4j-db:
    image: neo4j
    container_name: neo4j-db
    restart: always
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
    networks:
      - app-network

  tours-neo4j:
    image: neo4j:latest
    container_name: tours-neo4j
    restart: always
    environment:
      NEO4J_AUTH: neo4j/notverysecret
    ports:
      - "7475:7474"
      - "7688:7687"
    volumes:
      - tours-neo4j-data:/data
    networks:
      - app-network

  purchase-service:
    build:
      context: ./Backend/Purchase
      dockerfile: Dockerfile
    container_name: purchase
    restart: always
    depends_on:
      - purchase-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://purchase-db:5432/purchase_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    expose:
      - "8084"
    networks:
      - app-network

  purchase-db:
    image: postgres:16
    container_name: purchase-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: purchase_db
    volumes:
      - purchase-database-data:/var/lib/postgresql/data
    networks:
      - app-network

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
      - "14268:14268"
    networks:
      - app-network

  loki:
    image: grafana/loki:main-5206e3a
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - app-network

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:main
    container_name: fluent-bit
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./monitoring/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - loki
    networks:
      - app-network

  grafana:
    image: grafana/grafana:8.5.3
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - loki
    networks:
      - app-network

volumes:
  database-data:
    name: server-database
  blogs-database-data:
    name: blogs-database
  pgadmin-data:
    name: pgadmin-data
  neo4j-data:
    name: neo4j-data
  tours-neo4j-data:
    name: tours-neo4j-data
  purchase-database-data:
    name: purchase-database
  grafana-data:
    name: grafana-data

networks:
  app-network:
    driver: bridge