version: "3.7"
services:
  stakeholders-service:
    build: 
      context: ./Backend/Stakeholders
      dockerfile: Dockerfile
    container_name: stakeholders
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tourist_app
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - database-data:/var/lib/postgresql/data

  blogs-service:
    build:
      context: ./Backend/Blogs
      dockerfile: Blogs.API/Dockerfile
    container_name: blogs
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - blogs-database
    environment:
      - ConnectionStrings__DefaultConnection=Host=blogs-database;Database=blogs_db;Username=postgres;Password=root
    networks:
      - app-network

  blogs-database:
    image: postgres:16
    container_name: blogs-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: blogs_db
    ports:
      - "5433:5432"
    networks:
      - app-network
    volumes:
      - blogs-database-data:/var/lib/postgresql/data

  frontend:
    build: ./Frontend/tourist-app-front
    container_name: frontend
    ports:
      - "4200:4200"
    networks:
      - app-network
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - app-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin 

volumes:
  database-data:
    name: server-database
  blogs-database-data:
    name: blogs-database
  pgadmin-data:
    name: pgadmin-data

networks:
  app-network:
    driver: bridge